# Generated by Django 5.1.5 on 2025-01-29 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
