# Generated by Django 5.1.5 on 2025-02-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_alter_task_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='mark',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
