# Generated by Django 5.1.5 on 2025-02-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_task_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
