# Generated by Django 5.1.5 on 2025-02-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_task_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='mark_correct',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='task',
            name='mark_incorrect',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='task',
            name='mark_neutral',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
