# Generated by Django 5.1.5 on 2025-02-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_stats_best_streak_alter_stats_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='number',
        ),
        migrations.AddField(
            model_name='tasktest',
            name='number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
