# Generated by Django 5.1.5 on 2025-02-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0010_remove_task_number_tasktest_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='tasktest',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
