# Generated by Django 5.1.5 on 2025-02-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0011_alter_task_image_alter_tasktest_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='is_completed',
            field=models.BooleanField(),
        ),
    ]
