# Generated by Django 5.1.5 on 2025-02-15 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0012_alter_test_is_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='image',
        ),
    ]
