# Generated by Django 5.1.5 on 2025-02-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0013_remove_task_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='question',
            field=models.CharField(max_length=500),
        ),
    ]
