# Generated by Django 5.1.5 on 2025-02-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0014_alter_task_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='path',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
