# Generated by Django 5.1.5 on 2025-02-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0015_task_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='test_question',
            field=models.CharField(default=models.CharField(max_length=500), max_length=126),
        ),
    ]
